[package]
name = "simpl-syntax"
version = "0.1.0"
authors = ["Karl Meakin <karlwfmeakin@gmail.com>"]
edition = "2018"

[dependencies]
lalrpop-util = "0.19.0"
regex = "1"

[build-dependencies]
lalrpop = { version = "0.19.0", features = ["lexer"] }

[dev-dependencies]
insta = "0.16.1"
